apiVersion: apps/v1
kind: Deployment            # Correct
metadata:
  name: backend             # Valid name
  labels:
    app: task-management-backend
    tier: web
spec:
  replicas: 2               # Correct
  selector:
    matchLabels:
      app: task-management-backend          # Matches template labels ✔
  template:
    metadata:
      labels:
        app: task-management-backend
        tier: web
    spec:
      containers:
        - name: task-management-backend-container
          image: krishp234/task-management-backend:latest
          ports:
            - containerPort: 3000 
