services:
   db:
     image: mcr.microsoft.com/mssql/server:2025-latest
     volumes:
       - sql-server1:/var/opt/mssql
     environment:
       ACCEPT_EULA: Y
       MSSQL_SA_PASSWORD: Admin@123
     ports:
       - "1433:1433"

   task-management-backend:
     image: task-management-system:v2
     ports:
       - "3000:3000"
     depends_on:
       - db
   task-management-frontend:
     image: task-management-frontend
     ports:
       - "5173:5173"
     depends_on:
       - task-management-backend

volumes:
    sql-server1:
      external: true
