apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-management-frontend
  template:
    metadata:
      name: frotend-pod
      labels:
        app: task-management-frontend
        tier: web
    spec:
      containers:
        - name: frontend-container
          image: krishp234/task-management-frontend:latest
          ports:
            - containerPort: 5173
